# Generated by Django 3.2.5 on 2021-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_code',
            field=models.CharField(default='949295', max_length=6),
        ),
    ]
